neptune_project: bartholomew/car-racing
output_dir: outputs
agent:
  action_space:
    0: !!python/tuple
      - 0.
      - 1.
      - 0.
    1: !!python/tuple
      - 1.
      - .2
      - 0.
    2: !!python/tuple
      - -1.
      - .2
      - 0.
    3: !!python/tuple
      - 0.
      - 0.
      - 1.
max_epochs: 1000
max_time_steps: 1000
render: False
