neptune_project: bartholomew/car-racing
output_dir: outputs
agent:
  eps_decay: 1200
  eps_start: .95
  eps_end: .1
  action_space:
    0: !!python/tuple
      - 1.
      - .2
      - 0.
    1: !!python/tuple
      - -1.
      - .2
      - 0.
    2: !!python/tuple
      - 0.
      - .2
      - .4
    3: !!python/tuple
      - 0.
      - 1.
      - 0.
    4: !!python/tuple
      - 1.
      - .2
      - 0.
    5: !!python/tuple
      - -1.
      - .2
      - 0.
  network_kwargs:
    num_features: 4
  optimizer: Adam
  create_model: agents.models.cnn.FullyCNN
  batch_size: 256
max_epochs: 10000
max_time_steps: 1000
render: False
