neptune_project: bartholomew/car-racing
output_dir: outputs
agent:
  action_space:
    0: !!python/tuple
      - 0.
      - 0.
      - 0.
    1: !!python/tuple
      - 1.
      - 0.
      - 0.
    2: !!python/tuple
      - -1.
      - 0.
      - 0.
    3: !!python/tuple
      - 0.
      - 0.
      - .2
    4: !!python/tuple
      - 1.
      - 0.
      - .2
    5: !!python/tuple
      - -1.
      - 0.
      - .2
    6: !!python/tuple
      - 0.
      - 1.
      - 0.
    7: !!python/tuple
      - 1.
      - 1.
      - 0.
    8: !!python/tuple
      - -1.
      - 1.
      - 0.
    9: !!python/tuple
      - 0.
      - 1.
      - 0.
    10: !!python/tuple
      - 1.
      - 1.
      - 0.
    11: !!python/tuple
      - -1.
      - 1.
      - 0.
  network_kwargs:
    num_features: 8
  optimizer: Adam
max_epochs: 4000
max_time_steps: 1000
render: False
